"""empty message

Revision ID: 1899007f6573
Revises: 259646109f82
Create Date: 2021-01-02 14:39:36.417168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1899007f6573'
down_revision = '259646109f82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score_data', sa.Column('chefs', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score_data', 'chefs')
    # ### end Alembic commands ###
