"""empty message

Revision ID: 3475992126cb
Revises: 40e072933b42
Create Date: 2020-12-21 17:01:46.787440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3475992126cb'
down_revision = '40e072933b42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score_data', sa.Column('menu_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'score_data', 'menu', ['menu_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'score_data', type_='foreignkey')
    op.drop_column('score_data', 'menu_id')
    # ### end Alembic commands ###
