"""empty message

Revision ID: 40e072933b42
Revises: 86dab0281639
Create Date: 2020-12-21 17:01:18.031847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40e072933b42'
down_revision = '86dab0281639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('score_data_ibfk_1', 'score_data', type_='foreignkey')
    op.drop_column('score_data', 'menu_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score_data', sa.Column('menu_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('score_data_ibfk_1', 'score_data', 'menu', ['menu_id'], ['id'])
    # ### end Alembic commands ###
