"""empty message

Revision ID: 82be9614cb69
Revises: e5cabc3459d4
Create Date: 2021-01-05 14:27:09.825883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82be9614cb69'
down_revision = 'e5cabc3459d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'menu_num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('menu_num', mysql.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###
