"""empty message

Revision ID: a103d71c9416
Revises: 1899007f6573
Create Date: 2021-01-02 18:48:56.242500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a103d71c9416'
down_revision = '1899007f6573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('sold_out', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'sold_out')
    # ### end Alembic commands ###
