"""empty message

Revision ID: af3f52681e46
Revises: 0c3a4ecbaa85
Create Date: 2021-01-06 13:57:54.325661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af3f52681e46'
down_revision = '0c3a4ecbaa85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score_data', 'server')
    op.drop_column('score_data', 'suggest')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score_data', sa.Column('suggest', mysql.TEXT(), nullable=True))
    op.add_column('score_data', sa.Column('server', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
