"""empty message

Revision ID: c8d49439a7a1
Revises: 3475992126cb
Create Date: 2020-12-22 11:12:11.995151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d49439a7a1'
down_revision = '3475992126cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('ewm_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'ewm_name')
    # ### end Alembic commands ###
