"""empty message

Revision ID: e5cabc3459d4
Revises: a103d71c9416
Create Date: 2021-01-05 14:25:20.211459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5cabc3459d4'
down_revision = 'a103d71c9416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('menu_num', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'menu_num')
    # ### end Alembic commands ###
