"""empty message

Revision ID: ecf1b2ee4ebf
Revises: 60c5d07e92b2
Create Date: 2020-12-17 11:30:42.626419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf1b2ee4ebf'
down_revision = '60c5d07e92b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menu_name', sa.String(length=20), nullable=False),
    sa.Column('weighted_value', sa.Integer(), nullable=False),
    sa.Column('pic_name', sa.Text(), nullable=True),
    sa.Column('describe_info', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu')
    # ### end Alembic commands ###
