"""empty message

Revision ID: f1ddd1038170
Revises: ff055e1cf8e9
Create Date: 2021-01-05 16:35:06.513941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1ddd1038170'
down_revision = 'ff055e1cf8e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score_data', sa.Column('score', sa.Integer(), nullable=False))
    op.add_column('score_data', sa.Column('server', sa.Integer(), nullable=False))
    op.drop_column('score_data', 'score2')
    op.drop_column('score_data', 'score1')
    op.drop_column('score_data', 'score3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score_data', sa.Column('score3', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('score_data', sa.Column('score1', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('score_data', sa.Column('score2', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('score_data', 'server')
    op.drop_column('score_data', 'score')
    # ### end Alembic commands ###
