"""empty message

Revision ID: ff055e1cf8e9
Revises: 82be9614cb69
Create Date: 2021-01-05 14:27:56.459039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff055e1cf8e9'
down_revision = '82be9614cb69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('menu_num', sa.String(length=3), nullable=False))
    op.drop_column('menu', 'weighted_value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('weighted_value', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('menu', 'menu_num')
    # ### end Alembic commands ###
